[units]          
angle = 'deg'              # Units used for angles
length = 'mm'              # units used for lengths

[pcb]                      # PCB parameters
size_x = 45.0              # panel width 
size_y = 45.0              # panel height 
center_x = 72.5            # PCB center x-coord
center_y = 72.5            # PCB center y-coord

[pcb.led]                  # LED/Array specific parameters
dim = 20                   # LED Array dimension (dim x dim) array
angle = 225                # LED orientation
ref_prefix = 'D'           # Symbol prefix for panel headers
pattern = 'boustrophedon'  # LED layout pattern
#pattern = 'diagonal'       # LED layout pattern
step = 4                   # pattern step size (must be divisble by 2)










